CREATE DATABASE IF NOT EXISTS usersdb;

CREATE TABLE IF NOT EXISTS usersdb.users (
    user_id     INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    name        VARCHAR(25) NOT NULL,
    surname     VARCHAR(50) NOT NULL,
    email       VARCHAR(100) UNIQUE NOT NULL,
    telephone   VARCHAR(9) UNIQUE NOT NULL
);